# Makefile.in generated by automake 1.10.1 from Makefile.am.
# libpurple/protocols/fetion/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/pidgin
pkglibdir = $(libdir)/pidgin
pkgincludedir = $(includedir)/pidgin
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
subdir = libpurple/protocols/fetion
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in ChangeLog
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)
ARFLAGS = cru
libfetion_a_AR = $(AR) $(ARFLAGS)
libfetion_a_LIBADD =
am__libfetion_a_SOURCES_DIST = fetion.c fetion.h f_buddy.c f_buddy.h \
	f_chat.c f_chat.h f_gchat.c f_gchat.h f_zone.c f_zone.h \
	f_group.c f_group.h f_login.c f_login.h f_sysmsg.c f_sysmsg.h \
	f_portrait.c f_portrait.h f_user.c f_user.h f_util.c f_util.h \
	sipmsg.c sipmsg.h
am__objects_1 = libfetion_a-fetion.$(OBJEXT) \
	libfetion_a-f_buddy.$(OBJEXT) libfetion_a-f_chat.$(OBJEXT) \
	libfetion_a-f_gchat.$(OBJEXT) libfetion_a-f_zone.$(OBJEXT) \
	libfetion_a-f_group.$(OBJEXT) libfetion_a-f_login.$(OBJEXT) \
	libfetion_a-f_sysmsg.$(OBJEXT) \
	libfetion_a-f_portrait.$(OBJEXT) libfetion_a-f_user.$(OBJEXT) \
	libfetion_a-f_util.$(OBJEXT) libfetion_a-sipmsg.$(OBJEXT)
#am_libfetion_a_OBJECTS = $(am__objects_1)
libfetion_a_OBJECTS = $(am_libfetion_a_OBJECTS)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(pkgdir)"
pkgLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(pkg_LTLIBRARIES)
am__DEPENDENCIES_1 =
libfetion_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
am__libfetion_la_SOURCES_DIST = fetion.c fetion.h f_buddy.c f_buddy.h \
	f_chat.c f_chat.h f_gchat.c f_gchat.h f_zone.c f_zone.h \
	f_group.c f_group.h f_login.c f_login.h f_sysmsg.c f_sysmsg.h \
	f_portrait.c f_portrait.h f_user.c f_user.h f_util.c f_util.h \
	sipmsg.c sipmsg.h
am__objects_2 = fetion.lo f_buddy.lo f_chat.lo f_gchat.lo f_zone.lo \
	f_group.lo f_login.lo f_sysmsg.lo f_portrait.lo f_user.lo \
	f_util.lo sipmsg.lo
am_libfetion_la_OBJECTS = $(am__objects_2)
libfetion_la_OBJECTS = $(am_libfetion_la_OBJECTS)
libfetion_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libfetion_la_LDFLAGS) $(LDFLAGS) -o $@
am_libfetion_la_rpath = -rpath $(pkgdir)
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libfetion_a_SOURCES) $(libfetion_la_SOURCES)
DIST_SOURCES = $(am__libfetion_a_SOURCES_DIST) \
	$(am__libfetion_la_SOURCES_DIST)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/crow/source/pidgin/missing --run aclocal-1.10
ALLOCA = 
ALL_LINGUAS = af am ar az be@latin bg bn bs ca ca@valencia cs da de dz el en_AU en_CA en_GB eo es et eu fa fi fr ga gl gu he hi hu id it ja ka km kn ko ku lo lt mk mn my_MM nb ne nl nn oc pa pl pt_BR pt ps ro ru si sk sl sq sr sr@latin sv ta te th tr uk ur vi xh zh_CN zh_HK zh_TW
AMTAR = ${SHELL} /home/crow/source/pidgin/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/crow/source/pidgin/missing --run autoconf
AUTOHEADER = ${SHELL} /home/crow/source/pidgin/missing --run autoheader
AUTOMAKE = ${SHELL} /home/crow/source/pidgin/missing --run automake-1.10
AVAHI_CFLAGS = -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
AVAHI_LIBS = -lavahi-common -lavahi-client -lavahi-glib -lglib-2.0  
AWK = gawk
CATALOGS =  af.gmo am.gmo ar.gmo az.gmo be@latin.gmo bg.gmo bn.gmo bs.gmo ca.gmo ca@valencia.gmo cs.gmo da.gmo de.gmo dz.gmo el.gmo en_AU.gmo en_CA.gmo en_GB.gmo eo.gmo es.gmo et.gmo eu.gmo fa.gmo fi.gmo fr.gmo ga.gmo gl.gmo gu.gmo he.gmo hi.gmo hu.gmo id.gmo it.gmo ja.gmo ka.gmo km.gmo kn.gmo ko.gmo ku.gmo lo.gmo lt.gmo mk.gmo mn.gmo my_MM.gmo nb.gmo ne.gmo nl.gmo nn.gmo oc.gmo pa.gmo pl.gmo pt_BR.gmo pt.gmo ps.gmo ro.gmo ru.gmo si.gmo sk.gmo sl.gmo sq.gmo sr.gmo sr@latin.gmo sv.gmo ta.gmo te.gmo th.gmo tr.gmo uk.gmo ur.gmo vi.gmo xh.gmo zh_CN.gmo zh_HK.gmo zh_TW.gmo
CATOBJEXT = .gmo
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -g -O2
CHECK_CFLAGS =  
CHECK_LIBS = -lcheck  
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DATADIRNAME = share
DBUS_CFLAGS = -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
DBUS_LIBS = -L//lib -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
DBUS_SERVICES_DIR = ${datarootdir}/dbus-1/services
DEBUG_CFLAGS = -Wall  -DPURPLE_DISABLE_DEPRECATED -DPIDGIN_DISABLE_DEPRECATED -DFINCH_DISABLE_DEPRECATED -DGNT_DISABLE_DEPRECATED -Waggregate-return -Wcast-align -Wdeclaration-after-statement -Wendif-labels -Werror-implicit-function-declaration -Wextra -Wno-sign-compare -Wno-unused-parameter -Wformat-security -Werror=format-security -Winit-self -Wmissing-declarations -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wundef -Wp,-D_FORTIFY_SOURCE=2
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DOT = true
DOXYGEN = true
DSYMUTIL = 
DYNALOADER_A = 
DYNAMIC_PRPLS = bonjour gg irc jabber msn myspace novell oscar qq  simple yahoo zephyr
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EVOLUTION_ADDRESSBOOK_CFLAGS = 
EVOLUTION_ADDRESSBOOK_LIBS = 
EXEEXT = 
F77 = 
FFLAGS = 
GADU_CFLAGS = 
GADU_LIBS = 
GCONFTOOL = /usr/bin/gconftool-2
GCONF_SCHEMA_CONFIG_SOURCE = xml:merged:/etc/gconf/gconf.xml.defaults
GCONF_SCHEMA_FILE_DIR = $(sysconfdir)/gconf/schemas
GETTEXT_PACKAGE = pidgin
GLIB_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
GLIB_LIBS = -Wl,--export-dynamic -pthread -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0  
GMOFILES =  af.gmo am.gmo ar.gmo az.gmo be@latin.gmo bg.gmo bn.gmo bs.gmo ca.gmo ca@valencia.gmo cs.gmo da.gmo de.gmo dz.gmo el.gmo en_AU.gmo en_CA.gmo en_GB.gmo eo.gmo es.gmo et.gmo eu.gmo fa.gmo fi.gmo fr.gmo ga.gmo gl.gmo gu.gmo he.gmo hi.gmo hu.gmo id.gmo it.gmo ja.gmo ka.gmo km.gmo kn.gmo ko.gmo ku.gmo lo.gmo lt.gmo mk.gmo mn.gmo my_MM.gmo nb.gmo ne.gmo nl.gmo nn.gmo oc.gmo pa.gmo pl.gmo pt_BR.gmo pt.gmo ps.gmo ro.gmo ru.gmo si.gmo sk.gmo sl.gmo sq.gmo sr.gmo sr@latin.gmo sv.gmo ta.gmo te.gmo th.gmo tr.gmo uk.gmo ur.gmo vi.gmo xh.gmo zh_CN.gmo zh_HK.gmo zh_TW.gmo
GMSGFMT = /usr/bin/msgfmt
GNT_CFLAGS = 
GNT_LIBS = -lncurses -lpanel
GNT_LT_VERSION_INFO = 5:5:5
GNT_MAJOR_VERSION = 2
GNT_MICRO_VERSION = 5
GNT_MINOR_VERSION = 5
GNT_VERSION = gnt_display_version
GNUTLS_CFLAGS = -I/usr/include
GNUTLS_LIBS =  -lgnutls -lgcrypt
GREP = /bin/grep
GSTREAMER_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2  
GSTREAMER_LIBS = -pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lxml2 -lglib-2.0  
GTKSPELL_CFLAGS = 
GTKSPELL_LIBS = 
GTK_CFLAGS = -D_REENTRANT -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
GTK_LIBS = -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lgio-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lglib-2.0  
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INSTOBJEXT = .mo
INTLLIBS = 
INTLTOOL_EXTRACT = /usr/bin/intltool-extract
INTLTOOL_MERGE = /usr/bin/intltool-merge
INTLTOOL_PERL = /usr/bin/perl
INTLTOOL_UPDATE = /usr/bin/intltool-update
KRB4_CFLAGS = 
KRB4_LDFLAGS = 
KRB4_LIBS = 
LDADD = 
LDFLAGS = 
LIBOBJS = 
LIBPERL_A = 
LIBS = -lutil -lpthread -lnsl -lresolv 
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBXML_CFLAGS = -I/usr/include/libxml2  
LIBXML_LIBS = -lxml2  
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/crow/source/pidgin/missing --run makeinfo
MEANWHILE_CFLAGS = 
MEANWHILE_LIBS = 
MKDIR_P = /bin/mkdir -p
MKINSTALLDIRS = ./mkinstalldirs
MONO_CFLAGS = 
MONO_LIBS = 
MSGFMT = /usr/bin/msgfmt
MSGFMT_OPTS = -c
MSGMERGE = /usr/bin/msgmerge
NETWORKMANAGER_CFLAGS = 
NETWORKMANAGER_LIBS = 
NMEDIT = 
NSS_CFLAGS =  
NSS_LIBS =  
OBJEXT = o
PACKAGE = pidgin
PACKAGE_BUGREPORT = devel@pidgin.im
PACKAGE_NAME = pidgin
PACKAGE_STRING = pidgin 2.5.5
PACKAGE_TARNAME = pidgin
PACKAGE_VERSION = 2.5.5
PANGO_CFLAGS = -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
PANGO_LIBS = -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0  
PATH_SEPARATOR = :
PERL = 
PERL_CFLAGS = 
PERL_LIBS = 
PERL_MM_PARAMS = 
PKG_CONFIG = /usr/bin/pkg-config
PLUGINS_DEFINE = #define PURPLE_PLUGINS 1
POFILES =  af.po am.po ar.po az.po be@latin.po bg.po bn.po bs.po ca.po ca@valencia.po cs.po da.po de.po dz.po el.po en_AU.po en_CA.po en_GB.po eo.po es.po et.po eu.po fa.po fi.po fr.po ga.po gl.po gu.po he.po hi.po hu.po id.po it.po ja.po ka.po km.po kn.po ko.po ku.po lo.po lt.po mk.po mn.po my_MM.po nb.po ne.po nl.po nn.po oc.po pa.po pl.po pt_BR.po pt.po ps.po ro.po ru.po si.po sk.po sl.po sq.po sr.po sr@latin.po sv.po ta.po te.po th.po tr.po uk.po ur.po vi.po xh.po zh_CN.po zh_HK.po zh_TW.po
POSUB = po
PO_IN_DATADIR_FALSE = 
PO_IN_DATADIR_TRUE = 
PURPLE_LT_VERSION_INFO = 5:5:5
PURPLE_MAJOR_VERSION = 2
PURPLE_MICRO_VERSION = 5
PURPLE_MINOR_VERSION = 5
PURPLE_VERSION = purple_display_version
PYTHON = /usr/bin/python
PY_CFLAGS = -I/usr/include/python2.6
PY_LIBS = -lpython2.6 -L/usr/lib/python2.6/config
RANLIB = ranlib
SASL_LIBS = 
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SILC_CFLAGS = 
SILC_LIBS = 
SM_LIBS =  -lSM -lICE
SQLITE3_CFLAGS = 
SQLITE3_LIBS = 
SSL_CERTIFICATES_DIR = 
STARTUP_NOTIFICATION_CFLAGS = -I/usr/include/startup-notification-1.0  
STARTUP_NOTIFICATION_LIBS = -lstartup-notification-1  
STATIC_LINK_LIBS = 
STATIC_PRPLS = 
STRIP = strip
TCL_CFLAGS = 
TCL_LIBS = 
TK_LIBS = 
USE_NLS = yes
VERSION = 2.5.5
X11_CFLAGS =  
X11_LIBS = -lX11  
XGETTEXT = /usr/bin/xgettext
XMKMF = 
XSLTPROC = true
XSS_LIBS = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS =  -lSM -lICE
ZEPHYR_CFLAGS = 
ZEPHYR_LDFLAGS = 
ZEPHYR_LIBS = 
abs_builddir = /home/crow/source/pidgin/libpurple/protocols/fetion
abs_srcdir = /home/crow/source/pidgin/libpurple/protocols/fetion
abs_top_builddir = /home/crow/source/pidgin
abs_top_srcdir = /home/crow/source/pidgin
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
enable_dbus = yes
enable_devhelp = yes
enable_dot = yes
enable_doxygen = yes
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /home/crow/source/pidgin/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
perlpath = 
pidginpath = /usr/bin/pidgin
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
pythonpath = /usr/bin/python
sbindir = ${exec_prefix}/sbin
sedpath = /bin/sed
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = i686-pc-linux-gnu
target_alias = 
target_cpu = i686
target_os = linux-gnu
target_vendor = pc
top_build_prefix = ../../../
top_builddir = ../../..
top_srcdir = ../../..
EXTRA_DIST = \
		Makefile.mingw

pkgdir = $(libdir)/purple-$(PURPLE_MAJOR_VERSION)
FETIONSOURCES = \
	fetion.c \
	fetion.h \
	f_buddy.c  \
	f_buddy.h  \
	f_chat.c  \
	f_chat.h  \
	f_gchat.c \
	f_gchat.h \
	f_zone.c \
	f_zone.h \
	f_group.c  \
	f_group.h  \
	f_login.c  \
	f_login.h  \
	f_sysmsg.c \
	f_sysmsg.h \
       	f_portrait.c \
       	f_portrait.h \
       	f_user.c  \
       	f_user.h  \
	f_util.c  \
	f_util.h  \
	sipmsg.c \
	sipmsg.h

AM_CFLAGS = $(st) 
libfetion_la_LDFLAGS = -module -avoid-version
st = 
#st = -DPURPLE_STATIC_PRPL
#noinst_LIBRARIES = libfetion.a
#libfetion_a_SOURCES = $(FETIONSOURCES)
#libfetion_a_CFLAGS = $(AM_CFLAGS)
pkg_LTLIBRARIES = libfetion.la
libfetion_la_SOURCES = $(FETIONSOURCES)
libfetion_la_LIBADD = $(GLIB_LIBS)
AM_CPPFLAGS = \
	-I$(top_srcdir)/libpurple \
	-I$(top_builddir)/libpurple \
	$(GLIB_CFLAGS) \
	$(DEBUG_CFLAGS)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  libpurple/protocols/fetion/Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  libpurple/protocols/fetion/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libfetion.a: $(libfetion_a_OBJECTS) $(libfetion_a_DEPENDENCIES) 
	-rm -f libfetion.a
	$(libfetion_a_AR) libfetion.a $(libfetion_a_OBJECTS) $(libfetion_a_LIBADD)
	$(RANLIB) libfetion.a
install-pkgLTLIBRARIES: $(pkg_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(pkgdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgdir)"
	@list='$(pkg_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(pkgLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(pkgdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(pkgLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(pkgdir)/$$f"; \
	  else :; fi; \
	done

uninstall-pkgLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(pkg_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(pkgdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(pkgdir)/$$p"; \
	done

clean-pkgLTLIBRARIES:
	-test -z "$(pkg_LTLIBRARIES)" || rm -f $(pkg_LTLIBRARIES)
	@list='$(pkg_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libfetion.la: $(libfetion_la_OBJECTS) $(libfetion_la_DEPENDENCIES) 
	$(libfetion_la_LINK) $(am_libfetion_la_rpath) $(libfetion_la_OBJECTS) $(libfetion_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/f_buddy.Plo
include ./$(DEPDIR)/f_chat.Plo
include ./$(DEPDIR)/f_gchat.Plo
include ./$(DEPDIR)/f_group.Plo
include ./$(DEPDIR)/f_login.Plo
include ./$(DEPDIR)/f_portrait.Plo
include ./$(DEPDIR)/f_sysmsg.Plo
include ./$(DEPDIR)/f_user.Plo
include ./$(DEPDIR)/f_util.Plo
include ./$(DEPDIR)/f_zone.Plo
include ./$(DEPDIR)/fetion.Plo
include ./$(DEPDIR)/libfetion_a-f_buddy.Po
include ./$(DEPDIR)/libfetion_a-f_chat.Po
include ./$(DEPDIR)/libfetion_a-f_gchat.Po
include ./$(DEPDIR)/libfetion_a-f_group.Po
include ./$(DEPDIR)/libfetion_a-f_login.Po
include ./$(DEPDIR)/libfetion_a-f_portrait.Po
include ./$(DEPDIR)/libfetion_a-f_sysmsg.Po
include ./$(DEPDIR)/libfetion_a-f_user.Po
include ./$(DEPDIR)/libfetion_a-f_util.Po
include ./$(DEPDIR)/libfetion_a-f_zone.Po
include ./$(DEPDIR)/libfetion_a-fetion.Po
include ./$(DEPDIR)/libfetion_a-sipmsg.Po
include ./$(DEPDIR)/sipmsg.Plo

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

libfetion_a-fetion.o: fetion.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-fetion.o -MD -MP -MF $(DEPDIR)/libfetion_a-fetion.Tpo -c -o libfetion_a-fetion.o `test -f 'fetion.c' || echo '$(srcdir)/'`fetion.c
	mv -f $(DEPDIR)/libfetion_a-fetion.Tpo $(DEPDIR)/libfetion_a-fetion.Po
#	source='fetion.c' object='libfetion_a-fetion.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-fetion.o `test -f 'fetion.c' || echo '$(srcdir)/'`fetion.c

libfetion_a-fetion.obj: fetion.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-fetion.obj -MD -MP -MF $(DEPDIR)/libfetion_a-fetion.Tpo -c -o libfetion_a-fetion.obj `if test -f 'fetion.c'; then $(CYGPATH_W) 'fetion.c'; else $(CYGPATH_W) '$(srcdir)/fetion.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-fetion.Tpo $(DEPDIR)/libfetion_a-fetion.Po
#	source='fetion.c' object='libfetion_a-fetion.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-fetion.obj `if test -f 'fetion.c'; then $(CYGPATH_W) 'fetion.c'; else $(CYGPATH_W) '$(srcdir)/fetion.c'; fi`

libfetion_a-f_buddy.o: f_buddy.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_buddy.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_buddy.Tpo -c -o libfetion_a-f_buddy.o `test -f 'f_buddy.c' || echo '$(srcdir)/'`f_buddy.c
	mv -f $(DEPDIR)/libfetion_a-f_buddy.Tpo $(DEPDIR)/libfetion_a-f_buddy.Po
#	source='f_buddy.c' object='libfetion_a-f_buddy.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_buddy.o `test -f 'f_buddy.c' || echo '$(srcdir)/'`f_buddy.c

libfetion_a-f_buddy.obj: f_buddy.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_buddy.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_buddy.Tpo -c -o libfetion_a-f_buddy.obj `if test -f 'f_buddy.c'; then $(CYGPATH_W) 'f_buddy.c'; else $(CYGPATH_W) '$(srcdir)/f_buddy.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_buddy.Tpo $(DEPDIR)/libfetion_a-f_buddy.Po
#	source='f_buddy.c' object='libfetion_a-f_buddy.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_buddy.obj `if test -f 'f_buddy.c'; then $(CYGPATH_W) 'f_buddy.c'; else $(CYGPATH_W) '$(srcdir)/f_buddy.c'; fi`

libfetion_a-f_chat.o: f_chat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_chat.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_chat.Tpo -c -o libfetion_a-f_chat.o `test -f 'f_chat.c' || echo '$(srcdir)/'`f_chat.c
	mv -f $(DEPDIR)/libfetion_a-f_chat.Tpo $(DEPDIR)/libfetion_a-f_chat.Po
#	source='f_chat.c' object='libfetion_a-f_chat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_chat.o `test -f 'f_chat.c' || echo '$(srcdir)/'`f_chat.c

libfetion_a-f_chat.obj: f_chat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_chat.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_chat.Tpo -c -o libfetion_a-f_chat.obj `if test -f 'f_chat.c'; then $(CYGPATH_W) 'f_chat.c'; else $(CYGPATH_W) '$(srcdir)/f_chat.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_chat.Tpo $(DEPDIR)/libfetion_a-f_chat.Po
#	source='f_chat.c' object='libfetion_a-f_chat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_chat.obj `if test -f 'f_chat.c'; then $(CYGPATH_W) 'f_chat.c'; else $(CYGPATH_W) '$(srcdir)/f_chat.c'; fi`

libfetion_a-f_gchat.o: f_gchat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_gchat.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_gchat.Tpo -c -o libfetion_a-f_gchat.o `test -f 'f_gchat.c' || echo '$(srcdir)/'`f_gchat.c
	mv -f $(DEPDIR)/libfetion_a-f_gchat.Tpo $(DEPDIR)/libfetion_a-f_gchat.Po
#	source='f_gchat.c' object='libfetion_a-f_gchat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_gchat.o `test -f 'f_gchat.c' || echo '$(srcdir)/'`f_gchat.c

libfetion_a-f_gchat.obj: f_gchat.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_gchat.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_gchat.Tpo -c -o libfetion_a-f_gchat.obj `if test -f 'f_gchat.c'; then $(CYGPATH_W) 'f_gchat.c'; else $(CYGPATH_W) '$(srcdir)/f_gchat.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_gchat.Tpo $(DEPDIR)/libfetion_a-f_gchat.Po
#	source='f_gchat.c' object='libfetion_a-f_gchat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_gchat.obj `if test -f 'f_gchat.c'; then $(CYGPATH_W) 'f_gchat.c'; else $(CYGPATH_W) '$(srcdir)/f_gchat.c'; fi`

libfetion_a-f_zone.o: f_zone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_zone.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_zone.Tpo -c -o libfetion_a-f_zone.o `test -f 'f_zone.c' || echo '$(srcdir)/'`f_zone.c
	mv -f $(DEPDIR)/libfetion_a-f_zone.Tpo $(DEPDIR)/libfetion_a-f_zone.Po
#	source='f_zone.c' object='libfetion_a-f_zone.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_zone.o `test -f 'f_zone.c' || echo '$(srcdir)/'`f_zone.c

libfetion_a-f_zone.obj: f_zone.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_zone.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_zone.Tpo -c -o libfetion_a-f_zone.obj `if test -f 'f_zone.c'; then $(CYGPATH_W) 'f_zone.c'; else $(CYGPATH_W) '$(srcdir)/f_zone.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_zone.Tpo $(DEPDIR)/libfetion_a-f_zone.Po
#	source='f_zone.c' object='libfetion_a-f_zone.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_zone.obj `if test -f 'f_zone.c'; then $(CYGPATH_W) 'f_zone.c'; else $(CYGPATH_W) '$(srcdir)/f_zone.c'; fi`

libfetion_a-f_group.o: f_group.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_group.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_group.Tpo -c -o libfetion_a-f_group.o `test -f 'f_group.c' || echo '$(srcdir)/'`f_group.c
	mv -f $(DEPDIR)/libfetion_a-f_group.Tpo $(DEPDIR)/libfetion_a-f_group.Po
#	source='f_group.c' object='libfetion_a-f_group.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_group.o `test -f 'f_group.c' || echo '$(srcdir)/'`f_group.c

libfetion_a-f_group.obj: f_group.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_group.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_group.Tpo -c -o libfetion_a-f_group.obj `if test -f 'f_group.c'; then $(CYGPATH_W) 'f_group.c'; else $(CYGPATH_W) '$(srcdir)/f_group.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_group.Tpo $(DEPDIR)/libfetion_a-f_group.Po
#	source='f_group.c' object='libfetion_a-f_group.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_group.obj `if test -f 'f_group.c'; then $(CYGPATH_W) 'f_group.c'; else $(CYGPATH_W) '$(srcdir)/f_group.c'; fi`

libfetion_a-f_login.o: f_login.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_login.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_login.Tpo -c -o libfetion_a-f_login.o `test -f 'f_login.c' || echo '$(srcdir)/'`f_login.c
	mv -f $(DEPDIR)/libfetion_a-f_login.Tpo $(DEPDIR)/libfetion_a-f_login.Po
#	source='f_login.c' object='libfetion_a-f_login.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_login.o `test -f 'f_login.c' || echo '$(srcdir)/'`f_login.c

libfetion_a-f_login.obj: f_login.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_login.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_login.Tpo -c -o libfetion_a-f_login.obj `if test -f 'f_login.c'; then $(CYGPATH_W) 'f_login.c'; else $(CYGPATH_W) '$(srcdir)/f_login.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_login.Tpo $(DEPDIR)/libfetion_a-f_login.Po
#	source='f_login.c' object='libfetion_a-f_login.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_login.obj `if test -f 'f_login.c'; then $(CYGPATH_W) 'f_login.c'; else $(CYGPATH_W) '$(srcdir)/f_login.c'; fi`

libfetion_a-f_sysmsg.o: f_sysmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_sysmsg.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_sysmsg.Tpo -c -o libfetion_a-f_sysmsg.o `test -f 'f_sysmsg.c' || echo '$(srcdir)/'`f_sysmsg.c
	mv -f $(DEPDIR)/libfetion_a-f_sysmsg.Tpo $(DEPDIR)/libfetion_a-f_sysmsg.Po
#	source='f_sysmsg.c' object='libfetion_a-f_sysmsg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_sysmsg.o `test -f 'f_sysmsg.c' || echo '$(srcdir)/'`f_sysmsg.c

libfetion_a-f_sysmsg.obj: f_sysmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_sysmsg.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_sysmsg.Tpo -c -o libfetion_a-f_sysmsg.obj `if test -f 'f_sysmsg.c'; then $(CYGPATH_W) 'f_sysmsg.c'; else $(CYGPATH_W) '$(srcdir)/f_sysmsg.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_sysmsg.Tpo $(DEPDIR)/libfetion_a-f_sysmsg.Po
#	source='f_sysmsg.c' object='libfetion_a-f_sysmsg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_sysmsg.obj `if test -f 'f_sysmsg.c'; then $(CYGPATH_W) 'f_sysmsg.c'; else $(CYGPATH_W) '$(srcdir)/f_sysmsg.c'; fi`

libfetion_a-f_portrait.o: f_portrait.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_portrait.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_portrait.Tpo -c -o libfetion_a-f_portrait.o `test -f 'f_portrait.c' || echo '$(srcdir)/'`f_portrait.c
	mv -f $(DEPDIR)/libfetion_a-f_portrait.Tpo $(DEPDIR)/libfetion_a-f_portrait.Po
#	source='f_portrait.c' object='libfetion_a-f_portrait.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_portrait.o `test -f 'f_portrait.c' || echo '$(srcdir)/'`f_portrait.c

libfetion_a-f_portrait.obj: f_portrait.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_portrait.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_portrait.Tpo -c -o libfetion_a-f_portrait.obj `if test -f 'f_portrait.c'; then $(CYGPATH_W) 'f_portrait.c'; else $(CYGPATH_W) '$(srcdir)/f_portrait.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_portrait.Tpo $(DEPDIR)/libfetion_a-f_portrait.Po
#	source='f_portrait.c' object='libfetion_a-f_portrait.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_portrait.obj `if test -f 'f_portrait.c'; then $(CYGPATH_W) 'f_portrait.c'; else $(CYGPATH_W) '$(srcdir)/f_portrait.c'; fi`

libfetion_a-f_user.o: f_user.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_user.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_user.Tpo -c -o libfetion_a-f_user.o `test -f 'f_user.c' || echo '$(srcdir)/'`f_user.c
	mv -f $(DEPDIR)/libfetion_a-f_user.Tpo $(DEPDIR)/libfetion_a-f_user.Po
#	source='f_user.c' object='libfetion_a-f_user.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_user.o `test -f 'f_user.c' || echo '$(srcdir)/'`f_user.c

libfetion_a-f_user.obj: f_user.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_user.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_user.Tpo -c -o libfetion_a-f_user.obj `if test -f 'f_user.c'; then $(CYGPATH_W) 'f_user.c'; else $(CYGPATH_W) '$(srcdir)/f_user.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_user.Tpo $(DEPDIR)/libfetion_a-f_user.Po
#	source='f_user.c' object='libfetion_a-f_user.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_user.obj `if test -f 'f_user.c'; then $(CYGPATH_W) 'f_user.c'; else $(CYGPATH_W) '$(srcdir)/f_user.c'; fi`

libfetion_a-f_util.o: f_util.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_util.o -MD -MP -MF $(DEPDIR)/libfetion_a-f_util.Tpo -c -o libfetion_a-f_util.o `test -f 'f_util.c' || echo '$(srcdir)/'`f_util.c
	mv -f $(DEPDIR)/libfetion_a-f_util.Tpo $(DEPDIR)/libfetion_a-f_util.Po
#	source='f_util.c' object='libfetion_a-f_util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_util.o `test -f 'f_util.c' || echo '$(srcdir)/'`f_util.c

libfetion_a-f_util.obj: f_util.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-f_util.obj -MD -MP -MF $(DEPDIR)/libfetion_a-f_util.Tpo -c -o libfetion_a-f_util.obj `if test -f 'f_util.c'; then $(CYGPATH_W) 'f_util.c'; else $(CYGPATH_W) '$(srcdir)/f_util.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-f_util.Tpo $(DEPDIR)/libfetion_a-f_util.Po
#	source='f_util.c' object='libfetion_a-f_util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-f_util.obj `if test -f 'f_util.c'; then $(CYGPATH_W) 'f_util.c'; else $(CYGPATH_W) '$(srcdir)/f_util.c'; fi`

libfetion_a-sipmsg.o: sipmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-sipmsg.o -MD -MP -MF $(DEPDIR)/libfetion_a-sipmsg.Tpo -c -o libfetion_a-sipmsg.o `test -f 'sipmsg.c' || echo '$(srcdir)/'`sipmsg.c
	mv -f $(DEPDIR)/libfetion_a-sipmsg.Tpo $(DEPDIR)/libfetion_a-sipmsg.Po
#	source='sipmsg.c' object='libfetion_a-sipmsg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-sipmsg.o `test -f 'sipmsg.c' || echo '$(srcdir)/'`sipmsg.c

libfetion_a-sipmsg.obj: sipmsg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -MT libfetion_a-sipmsg.obj -MD -MP -MF $(DEPDIR)/libfetion_a-sipmsg.Tpo -c -o libfetion_a-sipmsg.obj `if test -f 'sipmsg.c'; then $(CYGPATH_W) 'sipmsg.c'; else $(CYGPATH_W) '$(srcdir)/sipmsg.c'; fi`
	mv -f $(DEPDIR)/libfetion_a-sipmsg.Tpo $(DEPDIR)/libfetion_a-sipmsg.Po
#	source='sipmsg.c' object='libfetion_a-sipmsg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libfetion_a_CFLAGS) $(CFLAGS) -c -o libfetion_a-sipmsg.obj `if test -f 'sipmsg.c'; then $(CYGPATH_W) 'sipmsg.c'; else $(CYGPATH_W) '$(srcdir)/sipmsg.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(LTLIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(pkgdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstLIBRARIES \
	clean-pkgLTLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-pkgLTLIBRARIES

install-dvi: install-dvi-am

install-exec-am:

install-html: install-html-am

install-info: install-info-am

install-man:

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-pkgLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-noinstLIBRARIES clean-pkgLTLIBRARIES ctags \
	distclean distclean-compile distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pkgLTLIBRARIES install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-pkgLTLIBRARIES

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
